name: OTC RSS mirror (lite)

on:
  schedule:
    - cron:  '*/15 * * * *'      # every 15 min
  workflow_dispatch:              # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Fetch full RSS (60-s timeout)
      run: >
        curl -sSL --max-time 60 --http1.1
        https://www.otcmarkets.com/syndicate/rss.xml -o rss_full.xml
        || curl -sSL --max-time 60 --http1.1
        https://content.otcmarkets.com/syndicate/rss.xml -o rss_full.xml

    - name: Trim to latest 150 items
      run: |
        awk '
          /<item>/ {c++}
          c<=150   {print}
          /<\/item>/ && c==150 {exit}
        ' rss_full.xml > rss_trimmed.xml
        echo "OTC RSS mirror fetched: $(date -u)" > latest_otc_rss.txt
        cat rss_trimmed.xml >> latest_otc_rss.txt

    - name: Commit & push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name  "github-actions[bot]"
        git add latest_otc_rss.txt
        git commit -m "chore: update trimmed RSS [skip ci]" || echo "no change"
        git push
