name: OTC RSS mirror
on:
  schedule:
    - cron: "*/15 * * * *"     # every 15 minutes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch RSS (primary or fallback, force HTTP/1.1)
        run: |
          set -e
          curl -sSL --http1.1 -o rss.xml \
            "https://www.otcmarkets.com/syndicate/rss.xml" \
            || curl -sSL --http1.1 -o rss.xml \
            "https://content.otcmarkets.com/syndicate/rss.xml"

      - name: Convert to plain text
        run: |
          {
            echo "OTC RSS mirror fetched: $(date -u)"
            echo
            cat rss.xml
          } > latest_otc_rss.txt
