# .github/workflows/rss.yml  (complete, ready to paste)

name: OTC-Positive-Impact-Report
on:
  workflow_dispatch:        # allow manual trigger
  schedule:
    - cron: '0 13 * * 1-5'  # 09:00 ET (13:00 UTC) on trading days

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    # 1) ----------  Fetch the latest RSS -------------------------------------------------
    - name: Fetch OTC RSS feed
      id: fetchrss
      run: |
        set -euo pipefail
        fetch() {                              # $1 = url
          echo "::group::Fetching $1"
          if curl --http1.1 -sSL --retry 3 --retry-delay 4 \
              --connect-timeout 15 "$1" -o feed.xml ; then
            if [ -s feed.xml ] && grep -q '<item>' feed.xml ; then
              echo "✅  Got feed from $1"
              echo "::endgroup::"
              return 0
            fi
          fi
          echo "⚠️  Feed empty or bad from $1"
          echo "::endgroup::"
          return 1
        }

        fetch "https://www.otcmarkets.com/syndicate/rss.xml" ||
        fetch "https://content.otcmarkets.com/syndicate/rss.xml"

    # 2) ----------  Trim to first 250 items (keeps header) -------------------------------
    - name: Trim feed (first 250 <item> nodes)
      run: |
        awk '
          BEGIN {c=0}
          /<item>/ {c++}
          {print}
          c==250 {print "</channel></rss>"; exit}
        ' feed.xml > feed_250.xml

    # 3) ----------  Set up Python environment -------------------------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install yfinance feedparser pandas tabulate

    # 4) ----------  Generate the report -------------------------------------------------
    - name: Generate OTC report
      run: |
        python scripts/generate_otc_report.py feed_250.xml > report.md

    # 5) ----------  Dump report to job summary ------------------------------------------
    - name: Publish report
      run: |
        echo "### OTC Positive-Impact News Report $(date -u '+%Y-%m-%d')" >> $GITHUB_STEP_SUMMARY
        cat report.md >> $GITHUB_STEP_SUMMARY
