name: OTC-Positive News

on:
  # 09:00 ET on US trading days (Mon-Fri)
  schedule:
    - cron: '0 13 * * 1-5'
  # enables manual “Run workflow” button
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    env:
      TZ: America/New_York      # guarantee ET timestamps

    steps:
    # ------------------------------------------------
    # 0) Checkout repo
    # ------------------------------------------------
    - uses: actions/checkout@v4

    # ------------------------------------------------
    # 1) Tools we need
    # ------------------------------------------------
    - name: Install XML & helper utilities
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils jq

    # ------------------------------------------------
    # 2) Download RSS feed (handles TLS-60 fallback)
    # ------------------------------------------------
    - name: Fetch OTC RSS feed
      id: fetch
      run: |
        set -euo pipefail

        # Helper that retries & handles TLS error-60 once with -k
        fetch() {
          local url="$1" tmp="$(mktemp)"
          echo "→ Trying $url"
          if curl -fsSL --retry 3 --retry-delay 2 "$url" -o "$tmp"; then
            echo "$tmp"; return 0
          fi
          rc=$?
          if [ "$rc" -eq 60 ]; then
            echo "TLS error 60 – retrying insecurely…" >&2
            curl -fsSLk --retry 3 --retry-delay 2 "$url" -o "$tmp"
            echo "$tmp"; return 0
          fi
          return "$rc"
        }

        # Primary then mirror
        FILE="$(fetch https://www.otcmarkets.com/syndicate/rss.xml || \
                 fetch https://content.otcmarkets.com/syndicate/rss.xml)"

        # Sanity: non-empty & well-formed XML
        [ -s "$FILE" ]           || { echo "Download empty"; exit 1; }
        xmllint --noout "$FILE"  || { echo "RSS not valid XML"; exit 1; }

        mv "$FILE" rss.xml
        echo "rss_path=rss.xml" >> "$GITHUB_OUTPUT"

    # ------------------------------------------------
    # 3) (optional) keep first 250 items
    # ------------------------------------------------
    - name: Trim feed to 250 items
      run: |
        awk 'BEGIN{n=0} /<item>/{n++} n<=250{print}' \
          "${{ steps.fetch.outputs.rss_path }}" > feed.xml

    # ------------------------------------------------
    # 4) Run your report-generator script
    # ------------------------------------------------
    - name: Generate OTC report
      run: |
        python scripts/generate_otc_report.py feed.xml
