name: OTC RSS mirror (lite)

on:
  schedule:
    - cron:  '*/15 * * * *'     # every 15 min
  workflow_dispatch:            # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # ---------------------------------------------------------------
    # 0.  Check out repo
    # ---------------------------------------------------------------
    - uses: actions/checkout@v3

    # ---------------------------------------------------------------
    # 1.  Fetch RSS (primary + fallback)
    # ---------------------------------------------------------------
    - name: Fetch RSS feed
      run: |
        set -e
        UA="Mozilla/5.0 ChatGPT‑RSS‑Mirror"
        curl -sSL --http1.1 \
             --connect-timeout 10 --max-time 40 --retry 3 --retry-delay 5 \
             -A "$UA" -o rss_full.xml \
             https://www.otcmarkets.com/syndicate/rss.xml || \
        curl -sSLk --http1.1 \
             --connect-timeout 10 --max-time 40 --retry 3 --retry-delay 5 \
             -A "$UA" -o rss_full.xml \
             https://content.otcmarkets.com/syndicate/rss.xml
        test -s rss_full.xml

    # ---------------------------------------------------------------
    # 2.  Trim to latest 250 <item> blocks
    #     + Python well‑formed‑ness check (fast, no deps)
    # ---------------------------------------------------------------
    - name: Trim and validate
      run: |
        # keep header + up to 250 <item> entries
        awk '
          /<item>/ {c++}
          c<=250   {print}
          /<\/item>/ && c==250 {exit}
        ' rss_full.xml > rss_trimmed.xml

        # sanity check: is it well‑formed XML?
        python - <<'PY'
import sys, xml.etree.ElementTree as ET
try:
    ET.parse("rss_trimmed.xml")
except ET.ParseError as e:
    print("Malformed XML:", e); sys.exit(1)
PY

        {
          echo "OTC RSS mirror fetched: $(date -u)"
          cat  rss_trimmed.xml
        } > latest_otc_rss.txt

    # ---------------------------------------------------------------
    # 3.  Commit & push only if the file actually changed
    # ---------------------------------------------------------------
    - name: Commit & push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name  "github-actions[bot]"
        git add latest_otc_rss.txt
        git diff --cached --quiet || git commit -m "chore: update trimmed RSS [skip ci]"
        git push
