name: OTC RSS mirror (lite)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch RSS feed
        shell: bash
        run: |
          set -e
          UA="Mozilla/5.0 ChatGPT-RSS-Mirror"
          curl -sSL --http1.1 \
               --connect-timeout 10 --max-time 40 --retry 3 --retry-delay 5 \
               -A "$UA" -o rss_full.xml \
               https://www.otcmarkets.com/syndicate/rss.xml || \
          curl -sSLk --http1.1 \
               --connect-timeout 10 --max-time 40 --retry 3 --retry-delay 5 \
               -A "$UA" -o rss_full.xml \
               https://content.otcmarkets.com/syndicate/rss.xml
          test -s rss_full.xml

      - name: Trim, wrap, and add XML wrappers
        shell: bash
        run: |
          awk '
            /<item>/ {c++}
            c<=250   {print}
            /<\/item>/ && c==250 {exit}
          ' rss_full.xml > items.xml

          {
            echo '<?xml version="1.0" encoding="UTF-8"?>'
            echo '<rss version="2.0"><channel>'
            cat items.xml
            echo '</channel></rss>'
          } > rss_full_valid.xml

          mv rss_full_valid.xml rss_trimmed.xml

      - name: Validate well‑formed XML
        shell: bash
        run: |
          python - <<'PY'
import xml.etree.ElementTree as ET, sys
try:
    ET.parse("rss_trimmed.xml")
except ET.ParseError as e:
    print("XML malformed:", e)
    sys.exit(1)
PY

      - name: Build mirror file
        shell: bash
        run: |
          {
            echo "OTC RSS mirror fetched: $(date -u)"
            cat rss_trimmed.xml
          } > latest_otc_rss.txt

      - name: Commit & push if changed
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add latest_otc_rss.txt
          if ! git diff --cached --quiet; then
            git commit -m "chore: update trimmed RSS [skip ci]"
            git push
          else
            echo "No change – skipping commit"
          fi
