name: OTC Positive-Impact Report

on:
  # manual trigger
  workflow_dispatch:
  # 09:00 ET on trading days (≈ 13:00 UTC; adjust for DST if needed)
  schedule:
    - cron: '0 13 * * 1-5'

jobs:
  otc-report:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository (needed if you commit results)
      - uses: actions/checkout@v4

      # 2️⃣ Fetch the RSS (primary → fallback)
      - name: Download OTC RSS feed
        run: |
          set -euo pipefail
          curl -fsSL https://www.otcmarkets.com/syndicate/rss.xml \
            -o rss.xml || \
          curl -fsSL https://content.otcmarkets.com/syndicate/rss.xml \
            -o rss.xml

      # 3️⃣ Trim to first 250 <item>s but keep header intact
      - name: Trim feed to 250 items
        run: |
          awk 'BEGIN{n=0}
               /<item>/{n++}
               {print}
               n==250 && /<\/item>/{exit}' rss.xml > rss_trimmed.xml
          # ▶ Patch: always close the RSS properly so XML is valid
          printf '</channel>\n</rss>\n' >> rss_trimmed.xml

      # 4️⃣ Run the Python script that parses & posts the report
      - name: Generate report
        env:
          YF_API_TOKEN: ${{ secrets.YF_API_TOKEN }}   # if your script needs it
        run: |
          python scripts/otc_report.py rss_trimmed.xml

      # 5️⃣ (Optional) Commit the generated report back to the repo
      - name: Commit report
        if: success()                      # only on success
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name  "GitHub Action"
          git add report.md
          git commit -m "Auto-update OTC report ($(date -u +'%Y-%m-%d'))" || echo "No changes"
          git push
